//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp_One.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaterOrder
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Guests { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public int Menu_Id { get; set; }
    
        public virtual Menu Menu { get; set; }
    }
}
