//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp_One.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CaterAddre
    {
        public int Id { get; set; }

        [Display(Name = "Street Address")]
        [Required(ErrorMessage = "Please Enter Street Address")]
        public string cStreetAddress { get; set; }

        [Display(Name = "City")]
        [Required(ErrorMessage = "Please Enter City")]
        public string cCity { get; set; }

        [Display(Name = "Country")]
        [Required(ErrorMessage = "Please Enter Country")]
        public string cCountry { get; set; }

       
        public string cZipCode { get; set; }

        [Display(Name = "Contact Number")]
        [Required(ErrorMessage = "Please Enter Contact Number")]
        public string cContactNumber { get; set; }

       
        public string cContactNumber2 { get; set; }
        public int Cater_Id { get; set; }
    
        public virtual Cater Cater { get; set; }
    }
}
