//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp_One.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_fypEntities : DbContext
    {
        public db_fypEntities()
            : base("name=db_fypEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cater> Caters { get; set; }
        public virtual DbSet<CaterAddre> CaterAddres { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<venue_rate> venue_rate { get; set; }
        public virtual DbSet<VenueAddress> VenueAddresses { get; set; }
        public virtual DbSet<VenueDate> VenueDates { get; set; }
        public virtual DbSet<VenueFeature> VenueFeatures { get; set; }
        public virtual DbSet<VenueInfo> VenueInfoes { get; set; }
        public virtual DbSet<VenueOrder> VenueOrders { get; set; }
        public virtual DbSet<CaterOrder> CaterOrders { get; set; }
    }
}
